### ISSUE TITLE
problemas

### ISSUE THREAD

**Issue by Miguelitoelmasbonito** [Michel-Mendoza/Test#1]
**PROBELMAS
PROBLEMAS
PROBLEMAS
PROBLEMAS**
<HTML>
PROBLEMAS
<BODY>
<>HACKEO<>
![Captura de pantalla 2024-09-19 203017](https://github.com/user-attachments/assets/1ed36200-49fa-487f-93fb-ff7fd3bb6680)
![Captura de pantalla 2024-09-19 203017](https://github.com/user-attachments/assets/2cf9d5f2-388e-455e-8fa0-38de653ac9d4)
![Captura de pantalla 2024-09-19 203017](https://github.com/user-attachments/assets/6ce15033-d326-4109-85d7-3cf6140d10e5)

**Comment by Michel-Mendoza** [comment]
tu mama
